import "vuetify/styles";
import "@mdi/font/css/materialdesignicons.css";
import { createVuetify } from "vuetify";
import {
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VNavigationDrawer,
  VMain,
  VLayout,
  VContainer,
  VRow,
  VCol,
  VSpacer,
  VCard,
  VCardItem,
  VCardTitle,
  VCardText,
  VCardActions,
  VForm,
  VAutocomplete,
  VTextField,
  VSelect,
  VTextarea,
  VFileInput,
  VList,
  VListItem,
  VListItemTitle,
  VBtn,
  VBtnGroup,
  VIcon,
  VCheckbox,
  VTable,
  VPagination,
  VMenu,
  VToolbar,
  VTabs,
  VTab,
  VDialog,
  VProgressCircular,
  VProgressLinear,
  VOverlay,
} from "vuetify/components";

export default createVuetify({
  theme: {
    defaultTheme: "dark",
  },
  aliases: {
    BFileInput: VFileInput,
    BTextField: VTextField,
    BTextarea: VTextarea,
    BSelect: VSelect,
    BAutocomplete: VAutocomplete,
    BBtn: VBtn,
    BLink: VBtn,
    BDialog: VDialog,
  },
  components: {
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VNavigationDrawer,
    VMain,
    VLayout,
    VContainer,
    VRow,
    VCol,
    VSpacer,
    VCard,
    VCardItem,
    VCardTitle,
    VCardText,
    VCardActions,
    VList,
    VListItem,
    VListItemTitle,
    VForm,
    VAutocomplete,
    VTextField,
    VTextarea,
    VFileInput,
    VBtn,
    VBtnGroup,
    VIcon,
    VCheckbox,
    VTable,
    VPagination,
    VMenu,
    VToolbar,
    VTabs,
    VTab,
    VSelect,
    VDialog,
    VProgressCircular,
    VProgressLinear,
    VOverlay,
  },
  defaults: {
    BTextField: {
      density: "compact",
      color: "error",
      variant: "outlined",
    },
    BFileInput: {
      prependInnerIcon: "$file",
      prependIcon: "",
      density: "compact",
      color: "error",
      variant: "outlined",
    },
    BTextarea: {
      density: "compact",
      color: "error",
      noResize: true,
      maxRows: 4,
      variant: "outlined",
    },
    BSelect: {
      density: "compact",
      color: "error",
      variant: "outlined",
    },
    BAutocomplete: {
      density: "compact",
      color: "error",
      variant: "outlined",
    },
    BBtn: {
      size: "large",
      color: "error",
      variant: "flat",
    },
    BLink: {
      variant: "plain",
    },
    BDialog: {
      transition: "scroll-x-transition",
      maxWidth: "500px",
    },
  },
});
